import { expect } from "chai";
import { Ajv2020 } from "ajv/dist/2020.js";
import addFormatsModule from "ajv-formats";
import { id } from "ethers";

import challengeSchema from "../../schemas/weight-challenge-evidence-v1.schema.json" with { type: "json" };
import manifestSchema from "../../schemas/weights-manifest-v1.schema.json" with { type: "json" };
import vector from "../../test-vectors/merkle.json" with { type: "json" };
import { buildWeightsManifest } from "../../scripts/lib/weights-manifest.js";

describe("Published JSON schemas", function () {
  const ajv = new Ajv2020({ allErrors: true, strict: true });
  addFormatsModule.default(ajv);
  const validateManifest = ajv.compile(manifestSchema);
  const validateChallenge = ajv.compile(challengeSchema);

  it("accepts the exact Manifest generated by the Pipeline library", function () {
    const manifest = buildWeightsManifest({
      datasetId: 7n,
      chainId: 84_532n,
      datasetRegistry: "0x1000000000000000000000000000000000000001",
      totalWeight: BigInt(vector.totalWeight),
      weightsRoot: vector.root,
      entries: vector.entries,
      pipelineVersion: "pipeline-v1.0.0",
      generatedAt: "2026-08-18T00:00:00.000Z",
      contentDigest: id("normalized-source-dataset"),
    });
    expect(validateManifest(manifest), JSON.stringify(validateManifest.errors)).to.equal(true);
  });

  it("accepts canonical Challenge Evidence and rejects noncanonical time", function () {
    const evidence = {
      schema: "main-protocol.weight-challenge-evidence.v1",
      datasetId: "7",
      chainId: "84532",
      datasetRegistry: "0x1000000000000000000000000000000000000001",
      weightsRoot: id("weights-root"),
      challenger: "0x2000000000000000000000000000000000000002",
      submittedAt: "2026-08-18T00:00:00.000Z",
      reason: "root-mismatch",
      summary: "The published root differs from the independently reproduced root.",
      artifacts: [{ uri: "ipfs://evidence", digest: id("evidence") }],
    };
    expect(validateChallenge(evidence), JSON.stringify(validateChallenge.errors)).to.equal(true);
    expect(validateChallenge({ ...evidence, submittedAt: "2026-08-18" })).to.equal(false);
  });
});
